{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "LatencyInHours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "latency_time_milliseconds_sum / latency_time_milliseconds_count / 1000 / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DeliveryTime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "delivery_time_milliseconds_sum / delivery_time_milliseconds_count / 1000 / 60 / 60 / 24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consume latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "method_timed_seconds_sum{class=\"com.bubusyaka.demo.service.OrderKafkaConsumer\",exception=\"none\",method=\"consumeMessage\"} / method_timed_seconds_count{class=\"com.bubusyaka.demo.service.OrderKafkaConsumer\",exception=\"none\",method=\"consumeMessage\"} * 1000",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}