global:
  scrape_interval: 2s
  scrape_timeout: 1s
  evaluation_interval: 2s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'app'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/actuator/prometheus'

